AllCops:
  TargetRubyVersion: 2.4

# Use double quotes ALL THE TIME!!!
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Disable Style/Documentation because...
Style/Documentation:
  Enabled: false

# Increase line length to 120
Metrics/LineLength:
  Max: 120

# Exclude class and method length for test
Metrics/BlockLength:
  Exclude:
    - "test/**/*"
Metrics/ClassLength:
  Exclude:
    - "test/**/*"
Metrics/MethodLength:
  Exclude:
    - "test/**/*"
